language: node_js
node_js:
  - "8"
before_script:
 - npm install
script:
 - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master