language: node_js
node_js:
  - "iojs"
  - "8"
before_script:
 - npm install
script:
 - "start"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master